### ISSUE TITLE
Using request(method, link, json)

### ISSUE THREAD

**Issue by tujger** [alirezaafkar/JsonRequester#1]
Hello,

I have some troubles using request(method, link, json). I set:

```
mBuilder.contentType(ContentType.TYPE_JSON);
JSONObject json = new JSONObject();
try {
   json.put("key1", "value1");
   json.put("key2", "value2");
} catch (JSONException e) {
   e.printStackTrace();
}
JsonObjectRequester mRequester = mBuilder.buildObjectRequester(new Requester(callback));
mRequester.request(Methods.GET, link, json);

```
And i got nothing but header on my server. What should i do to get this json?

Edward.

**Comment by alirezaafkar** [comment]
@tujger Hi, For adding this values to header you have to use the following code:
`mBuilder.header(json);`
_or_
`mBuilder.addToHeader("key1","value1");`
